### ISSUE TITLE
Help with $PATH

### ISSUE THREAD

**Issue by awakekat** [albertinad/brackets-bower#45]
After installing the plugin I get a warning error that brackets cant find git in the path. I use ohmyzsh and am able to get to my .zshrc file to make changes but I do not know what changes to make.

echo $PATH = is 3 lines long the width of my monitor and I know that can't be right, but here it is:
/usr/local/git/bin:/usr/local/git/bin:/usr/local/git/bin:/usr/local/git/bin:/usr/local/git/bin:/usr/local/git/bin/git:/usr/local/heroku/bin:/usr/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/username/.rvm/bin:/Users/username/.rvm/bin:/Users/username/.rvm/bin:/Users/username/.rvm/bin:/Users/username/.rvm/bin:/Users/username/.rvm/bin:/Users/username/.rvm/bin
(This looks wacky to me with so many repeats)

I had a problem updating git to the new version of gitand had to take some didfficult steps to make the new version take - I kept checking the version number and it would stay after updating. Since then things are not working properly. HELP Please?! <3

In the .zshrc file:
export PATH=/usr/local/git/bin:$PATH

FYI - this problem is on all 3 of my macs. Would really like help fixing this.

**Comment by albertinad** [comment]
Hi @awakekat ! Can you open a terminal and type `git --version` and paste the output here? Thanks!

**Comment by awakekat** [comment]
2.2.1

**Comment by e-cloud** [comment]
me too, ``git --version``
``// output:   git version 1.9.5.msysgit.0``

**Comment by albertinad** [comment]
@e-cloud can you share the console output? Debug -> Show Developer Tools (F12) -> Console Tab
Thanks!

**Comment by e-cloud** [comment]
i checked the DevTool, and found nothing about bower.
But i feel very sorry, when i restart my PC, bower extension works.
it may be because of my reinstallation for git and the lazy-updated path

**Comment by awakekat** [comment]
I have restarted and I still get the error when installing Brackets Bower... When trying to install a bower package it gets stuck - obviously can't find git path...

**Comment by albertinad** [comment]
Hi @awakekat , sorry for the delay on the fix, I setup an environment in mac, so I can fix this ASAP, can you share the output of console please? If there's something that can help me.

**Comment by awakekat** [comment]
Hope this is what you wanted:

/thirdparty/react.js:4356 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/SASSAgent.js:161:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/main.js:322:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.<anonymous> (file:///Users/MiniKat/Library/Application%20Support/Brackets/extensions/user/sbruchmann.static-preview/server/ServerManager.js:12:27)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:123:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:124:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:125:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _statusChangeHandler (/SASSAgent.js:141:49)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _setStatus (/LiveDevelopment/LiveDevelopment.js:329:17)
    at Object.init (/LiveDevelopment/LiveDevelopment.js:1487:9)
    at eval (/LiveDevelopment/main.js:308:25)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/command/KeyBindingManager.js:740 Cannot assign Alt-Cmd-B to io.emmet.balance_outward. It is already assigned to com.adobe.brackets.commands.bower.installFromBower
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at init (file:///Users/MiniKat/Library/Application%20Support/Brackets/extensions/user/brackets-emmet/main.js:245:3)
    at loadExtensions (file:///Users/MiniKat/Library/Application%20Support/Brackets/extensions/user/brackets-emmet/main.js:169:4)
    at file:///Users/MiniKat/Library/Application%20Support/Brackets/extensions/user/brackets-emmet/main.js:264:3
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/filesystem/impls/appshell/AppshellFileSystem.js:441 Blind write attempted:  /Users/MiniKat/Desktop/sandbox/.brackets.json 1425513486000 null
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object.registerMainPanel (/./MainPanel.js:285:9)
    at _appReadyHandler (/main.js:281:19)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at Object._initParfaitControlsPopup [as initParfaitControlsPopup] (/./ParfaitPopup.js:112:9)
    at _appReadyHandler (/main.js:282:22)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:285:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _attachExtensionManagerListener (/main.js:118:9)
    at _appReadyHandler (/main.js:289:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _setupAbandonmentEvents (/main.js:234:9)
    at _appReadyHandler (/main.js:291:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:294:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)

**Comment by awakekat** [comment]
So here is a question... I am trying to fix my $PATH, what does yours look like? when I type 'which bower', I get /usr/local/bin/bower - so it is there but it must not be in the path for  Brackets to find. I have manually added the bower path to $PATH and it looks like this:

export PATH=/usr/local/bin:/usr/local/git/bin:/usr/local/bin/bower:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

Is there something out of order or missing??

Thanks

**Comment by awakekat** [comment]
Ok it's late and I have been working at this too long. The error I am getting now is that the plugin cannot find git. I type 'which git' and get '/usr/local/git/bin/git'
and my path= '/usr/local/bin:/usr/local/git/bin/git:/usr/local/bin/bower:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'

I have uninstalled and reinstall the bower plugin each time I have made changes to the $PATH to check if it finds it - not so.

So if someone has a working plugin please let me know what your path says...

**Comment by albertinad** [comment]
There's no need to have bower installed on the system, because the extension provides one. I'm trying to reproduce this on my mac, today I will try to have an answer for you.

**Comment by awakekat** [comment]
Tinkering some more...
So this morning I went to bower install a package in the terminal and bower couldn't find git - What the...!! So I put the default git path as the very first entry - /usr/local/git/bin 
Then I was able to see the path with 'which git' but it gave me - /usr/local/git/bin/git
so I put that at the end of the path, but brackets bower is still not happy...

**Comment by albertinad** [comment]
and with that change to the PATH variable, did you try to run `bower install` from the console?

**Comment by awakekat** [comment]
No because with a new install of the bower plugin I got the  same error trying to find git, but I gave it a try and got this:
![screen shot 2015-03-12 at 12 42 15 pm](https://cloud.githubusercontent.com/assets/5148843/6622799/4cc658d0-c8b5-11e4-8b87-2c37b8a01d4d.png)

**Comment by awakekat** [comment]
With the plugin installed, opening Brackets shows this error every time:

![screen shot 2015-03-12 at 12 44 14 pm](https://cloud.githubusercontent.com/assets/5148843/6622856/aeae052a-c8b5-11e4-91a6-abad282e6c2c.png)

**Comment by albertinad** [comment]
Sorry! I mean running `bower install jquery` from a OS terminal/console.

**Comment by albertinad** [comment]
The output of `echo $PATH` on the terminal of my mac is the following:
`/usr/bin:/bin:/usr/sbin:/usr/local/bin:/opt/x11/bin:/usr/local/git/bin`
and the output of `which git`:
`/usr/bin/git`

**Comment by albertinad** [comment]
Can you try to modify your env PATH variable, to include this path `/usr/local/git/bin` instead of the path to the binary directly, `/usr/local/git/bin/git`. But make that change directly to the `/etc/paths`.

**Comment by awakekat** [comment]
I am with you until the part: "But make that change directly to the /etc/paths." Where is that located?

**Comment by albertinad** [comment]
I mean that you can try open the file `paths`, located at `/etc` (I'm not really sure if that is a common location for the file in mac no matter the version of the OS).
Another question, may be a dummy one, did you export the modified PATH variable on the terminal instance that you're running bower and git, or did you just update some file like bash_profile for your user?

Sorry to insist on this :) but I need to understand if this is a problem from my extension or bower to locate git in your system. If you run the command `bower install jquery` in a terminal and get an error, it's a path problem.

**Comment by awakekat** [comment]
Yes in my mac terminal I can type ‘bower install jquery’ and it works.

I do have a bash profile manager .zsh and the .zshrc file is the one I am using to update the path. Outside of that process I don’t know where else on a mac the PATH would be listed. I did look around for a /etc and didn’t find one even in the hidden files. 

If the plugin is looking for git and can’t find it in the “normal location”, is there a preference in the plugin to override and enter the new path??

**Comment by albertinad** [comment]
The extension uses node child_process.exec to run `git --version`. If that doesn't work, is not a really big problem, just improving the mechanism of detection of git would be enough. My concern is that internally, bower from the extension can't find git.
Internally, bower (provided through the extension) uses child_process.spawn to run git commands. It doesn't allow to specify the git executable, it just assume that git is available at the system level. I never changed that, cause I'm providing the current version of bower that is released, and I didn't changed the version it for about months. It is the latest one. 
Can you provide me the version of mac OS that you're using?

**Comment by albertinad** [comment]
And what about creating a `.bash_profile` file and there export PATH containing `/usr/local/git/bin` at first?

**Comment by awakekat** [comment]
Yosemite 10.10.2

**Comment by awakekat** [comment]
Did what you suggested with the .bash_profile - no dice error still pops up

**Comment by albertinad** [comment]
Could you please load [this](https://drive.google.com/file/d/0B2qjL2i00DnjM3FCYlNfSl9lZmM/view?usp=sharing) version of the extension? Just in case, make sure to uninstall the previous version.
This version only add a logger to the node domain, you can try adding a bower.json file to your project, add some dependencies to install, then run install from the extension panel and wait until it fails. Then, after failing to installing the packages, go to your user home directory, and it should be there the file `brackets-bower.log`. Please share the content with me. If that file wasn't created, open CDT on brackets and paste the output here.

Thanks!

**Comment by awakekat** [comment]
I manually installed and placed the contents of the zip file folder in Library/Application SupportBrackets/extensions/user

Got the error.  Used the plugin to create the bower.json and the bowerrc file

Could not find anywhere on the mac the brackets-bower.log file so here is the contents of the CDT:

NodeDebugUtils.js:117 [node-log 11:47:58 PM] [31m[2015-03-13 23:47:58.729] [ERROR] brackets-bower - [39m[install command]
2015-03-13 23:47:58.734NodeDebugUtils.js:117 [node-log 11:47:58 PM] [31m[2015-03-13 23:47:58.731] [ERROR] brackets-bower - [39m{ [Error: git is not installed or not in the PATH]
  code: 'ENOGIT',
  data: 
   { endpoint: 
      { name: 'foundation',
        source: 'zurb/bower-foundation',
        target: '*' } } }
Error: git is not installed or not in the PATH
    at createError (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/util/createError.js:4:15)
    at GitHubResolver.GitResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitResolver.js:34:15)
    at GitHubResolver.GitRemoteResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:10:17)
    at new GitHubResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitHubResolver.js:12:23)
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolverFactory.js:24:16
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:1142:26
    at _fulfilled (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:749:13)
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:509:49
2015-03-13 23:48:04.526NodeDebugUtils.js:117 [node-log 11:48:04 PM] [31m[2015-03-13 23:48:04.524] [ERROR] brackets-bower - [39m[install command]
2015-03-13 23:48:04.528NodeDebugUtils.js:117 [node-log 11:48:04 PM] [31m[2015-03-13 23:48:04.525] [ERROR] brackets-bower - [39m{ [Error: git is not installed or not in the PATH]
  code: 'ENOGIT',
  data: 
   { endpoint: 
      { name: 'foundation',
        source: 'zurb/bower-foundation',
        target: '*' } } }
Error: git is not installed or not in the PATH
    at createError (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/util/createError.js:4:15)
    at GitHubResolver.GitResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitResolver.js:34:15)
    at GitHubResolver.GitRemoteResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:10:17)
    at new GitHubResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitHubResolver.js:12:23)
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolverFactory.js:24:16
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:1142:26
    at _fulfilled (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:749:13)
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:509:49
2015-03-13 23:48:45.894NodeDebugUtils.js:117 [node-log 11:48:45 PM] [31m[2015-03-13 23:48:45.892] [ERROR] brackets-bower - [39m[list command]
2015-03-13 23:48:45.896NodeDebugUtils.js:117 [node-log 11:48:45 PM] [31m[2015-03-13 23:48:45.894] [ERROR] brackets-bower - [39m{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
2015-03-13 23:49:57.490NodeDebugUtils.js:117 [node-log 11:49:57 PM] [31m[2015-03-13 23:49:57.487] [ERROR] brackets-bower - [39m[install command]
2015-03-13 23:49:57.493NodeDebugUtils.js:117 [node-log 11:49:57 PM] [31m[2015-03-13 23:49:57.490] [ERROR] brackets-bower - [39m{ [Error: git is not installed or not in the PATH]
  code: 'ENOGIT',
  data: 
   { endpoint: 
      { name: 'foundation',
        source: 'zurb/bower-foundation',
        target: '*' } } }
Error: git is not installed or not in the PATH
    at createError (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/util/createError.js:4:15)
    at GitHubResolver.GitResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitResolver.js:34:15)
    at GitHubResolver.GitRemoteResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:10:17)
    at new GitHubResolver (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolvers/GitHubResolver.js:12:23)
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/bower/lib/core/resolverFactory.js:24:16
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:1142:26
    at _fulfilled (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:749:13)
    at /Users/katherinewakefield/Library/Application Support/Brackets/extensions/user/brackets-bower-0.2.2-logger/node/node_modules/q/q.js:509:49

**Comment by albertinad** [comment]
mmm good, just one more time, but with [this](https://drive.google.com/file/d/0B2qjL2i00Dnjam5pYkxnNWhER0U/view?usp=sharing) package. Remove manually the previous version installed, and please, before opening brackets, open a terminal and run `bower cache clean`.
After the error let me see the console output. Sorry to keep you with this, but I'm not able to reproduce it :( and I want to help you.

**Comment by albertinad** [comment]
Hi @awakekat any news related to this path problem? do you still have this issue?

**Comment by awakekat** [comment]
Yes, that I can duplicate the same problem on windows too.

**Comment by albertinad** [comment]
Now windows too... ok, could you try the zip that I shared with you? If you have the time to try it, then share the CDT output so I can help you. I'm still not able to reproduce it.

**Comment by awakekat** [comment]
I am going to close this since I seem to be the only one with this problem.

**Comment by eappell** [comment]
Sorry, but I'm having the same issue in Windows 7, and I can't find anywhere else where this is mentioned so I'm going to add a comment here.  Hopefully it will get seen even though this is closed...?

When I open Brackets I get the same big error saying "Git wasn't found on your system".  I've checked my PATH and git is definitely in there, and when I run `git --version` I get `git version 1.9.5.msysgit.1` from any directory I happen to be in, so I believe the PATH is correct.  So what can I do to resolve this startup error?

Thanks!

**Comment by albertinad** [comment]
Hi @eappell , I'm re-opening this issue since it seems that can be a common problem. 
Please, can you try [this](https://drive.google.com/file/d/0B2qjL2i00Dnjam5pYkxnNWhER0U/view) version of the extension? Before, remove the current installed version. 
Try to perform the same steps to reproduce the error message. Then, create a bower.json file for your project, add one dependency and then click on `install` in the bower panel. Let's wait what happened, once it fails or install it. Open brackets CDT, and paste the content here. Or better, if you have available `brackets-bower.log` file in your home directory, share it with me so I can analyze what is going on.

Thanks!

**Comment by eappell** [comment]
Hi @albertinad - As I mentioned, I cannot uninstall the extension using the extension manager in Brackets, as it gives me the error.  So I moved the extension folder from user to disabled, then restarted Brackets.  What I found was that I still cannot update any extensions.  Also, I cannot install any new extensions.  So I believe my extension manager has become corrupted.  I did drop the new version of the extension into the user folder and start Brackets back up, but I am still getting the Bower Warning message...  The only steps I did was to start Brackets.  I don't even have a bower.json file in the currently open project...

**Comment by albertinad** [comment]
It sounds like a brackets problem, but let try a few things!:
1) If you don't have a bower.json file, create one using the bower extension panel
2) Install some dependencies through that file
3) Find the `brackets-bower.log` file and share to me so I can read the logs. 
The main reason that I want you to install a bower dependency, is to know if bower is able to spawn git. If that is not the case, get the error message, since I can't reproduce it on any environment.

The 'git not found' message from bower extension appears also when there is some problem with node domains in brackets. I need to improve that message.

Thanks!

**Comment by eappell** [comment]
Ok, the issue I was having is that my proxy server was enabled (I'm in Windows 7) and Brackets couldn't get through it for anything.  As soon as I disabled it everything started to work again.  I was able to update my extensions, and I did add a bower.json file to the project, and all of the dependencies that I added were installed without issue.  

I would post the log file, but I can't find it anywhere - where should it be on a Windows machine?  There is no "Home" directory as there is on a Mac or Linux.  It's not in my user directory or the AppData directory, that I can see...?  Thanks!

**Comment by albertinad** [comment]
Ahh I see! Still, I will improve that warning message from bower extension.
I believe, that you can found the log file location in brackets CDT. When the extension is loaded and the node domain connection from the extension is ready, at that point, the location of the file might be logged in the CDT output. Sorry for that!, it was a quick/dirty implementation so I can get information from the node process code related to this issue.

**Comment by albertinad** [comment]
Hi @awakekat , if the issue is still there, can you try the (latest)[https://github.com/albertinad/brackets-bower/releases/tag/v0.2.9] version available? If the git warning shows up or not, try to install something from the bower.json, if it fails, you should see an error dialog with detail explanation.
I'm wondering, if you have installed also brackets-git extension and when you open brackets an error/warning from that extension is also available. Both extensions relies on git available in the system PATH, and both performs mostly the same validation for checking git.

Please, keep me up to date with this, I want this issue resolved :)

Thanks!

**Comment by albertinad** [comment]
In the case of windows, the [recommendation](https://github.com/bower/bower#windows-users) from bower team, is to install it with the option `Run Git from the windows command prompt`

**Comment by awakekat** [comment]
I manually installed the contents of the zip into the Mac: Library > Application Support > Brackets > user folder

Here are the lines in my .zshrc file:

export PATH=/usr/bin:/bin:/usr/sbin:/usr/local/bin:/opt/x11/bin:/usr/local/git/bin

These other attempts are commented out:
#export PATH=/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/git/bin/git
#export PATH=/usr/local/git/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH”

When I type echo $PATH in terminal I get:
/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/usr/local/bin:/opt/x11/bin:/usr/local/git/bin:/Users/katherinewakefield/.rvm/bin

I know that this path has : as a separator for added paths. Can this be pruned? I installed heroku and it was over my head - can this path be deleted?

When I type which git:
/usr/local/git/bin/git

I have entered this address into both the .zshrc file and the .bash_profile

When I type 'which git' again, I get git not found

In looking around I found this about which git:
'this will give the path of the git binary file not the git installation directory’

If I go back and change the git path to: /usr/local/git/bin - "which git” works showing the path

What I don't understand is where the heroku is coming from, every other path is designated either in .zshrc file and or replicated in the .bash_profile file. Here is a question, how do I know which file is the default bash file for OSX?

I am using iTerm2 and ohmyzsh. Could there be an error in iTerm somewhere? I only say this since at one time your extension did work in brackets no problem. I have switched from terminal to iTerm and back again.

I still feel my case is isolated and something is messed up in my setup… No worries, I am sure you would like to have it work but I have a quick keyboard shortcut that opens terminal and I type the bower command there. 

Happy Coding!	
Katherine

**Comment by awakekat** [comment]
Finally Good News!! I got brackets-bower to work on Windows! I followed these instructions: http://www.chambaud.com/2013/07/08/adding-git-to-path-when-using-github-for-windows/
and I didn't get the error. Now on to do the same for Mac since I use it every day.

**Comment by albertinad** [comment]
Great news!! :D do you have any updates related on Mac?
Thanks!

**Comment by awakekat** [comment]
Nope not yet. It probably has taken me this long to ask the right question. Where does Brackets look for PATH - what is the name of the file that Brackets is looking for to find the path to git? I think that is my problem since I am using OhMyZSH and iTerm. I am controlling my PATH through a .zshrc file and have located the path to git /usr/local/git/bin/git from typing 'which git'. I have added this path to the .bashrc file too and I am still getting the error. So I am not pointing to the right file that Brackets is looking for the PATH.

**Comment by infin80** [comment]
FYI...I'm following this like it's a nail-biting thriller. I'm having the same Yosemite 10.10.3 Mac issues and I'm dying to see how this plays out!!!! BTW my `which git` returns `/usr/local/bin/git` if that helps anyone

**Comment by awakekat** [comment]
I found this article which may or may not help: http://www.sublimelinter.com/en/latest/troubleshooting.html#debugging-path-problems

But it did send me digging again. So I typed 'echo $SHELL' and got /bin/zsh. By the article I went to see the contents of .zprofile which said 'echo profile'.

I went to both .profile and .bash_profile that had the wrong git path for me - changed both and still getting error in Bower Brackets.

.bashrc has the right git path
changed .zshrc-e

There are no other files! ARGH!!

**Comment by MagicLo** [comment]
I have the same issue with my Yosemite 10.10.3, any luck?

**Comment by awakekat** [comment]
No luck yet. I have given up and just use the terminal. Please post if a solution arises.

Thanks

**Comment by MagicLo** [comment]
My issue solved:
1.Delete bower.json
2.Follow this article : http://nielsvanrongen.com/bower-exit-code-of-69.html
3.Rerun Brackets

I hope it help.

**Comment by awakekat** [comment]
Not the problem. xcode already agreed to. Still have this same error on 3 different macs:
git issue
![screen shot 2015-07-23 at 9 43 22 am](https://cloud.githubusercontent.com/assets/5148843/8851766/7ebc699c-311f-11e5-9f33-e54fc91d6e16.png)

**Comment by eip** [comment]
On OS X 10.10 having similar problem with Brackets Shell extension (https://github.com/johnhidey/hdy.brackets-shell/).

With "echo $PATH" command found that PATH variable inside Brackets environment differs from OS shell. Its set to "/usr/bin:/bin:/usr/sbin:/sbin" and does not include "/usr/local/bin" directory.

I temporary fixed it by adding this code:

```js
if (process.env.PATH.indexOf('/usr/local/bin') === -1) {
    process.env["PATH"] = '/usr/local/bin:' + process.env["PATH"];
}
```

to the "/Applications/Brackets.app/Contents/node-core/Launcher.js" file (after lines setting the process.env["TMPDIR"]).

**Comment by stacyk** [comment]
I have had this same problem for a while now as well running on a Mac with OS X Yosemite (10.10.5), using ZSH instead of Bash. Hoping to check some of these links out to find a solution. I'll post my results.

**Comment by albertinadx** [comment]
Hi @stacyk thanks for helping! I have an available Mac now with OS X Yosemite (but lateste version 10.11.1), I will set up my environment and instead of using Bash I will use ZSH so I can try to reproduce it.

**Comment by albertinad** [comment]
Hi! thanks for helping! I have an available Mac now with OS X Yosemite (but lateste version 10.11.1), I will set up my environment and instead of using Bash I will use ZSH so I can try to reproduce it.

**Comment by albertinad** [comment]
Hi @stacyk , can you please follow the steps in the issue #80 , with the pre-release version of the extension and share the logs?

Thanks!
